### ISSUE TITLE
'POCSAG_1b_4d5' is not a member of 'RH_RF24'

### ISSUE THREAD

**Issue by mjkdz** [jumbo77/pocsage_si4463#1]
'POCSAG_1b_4d5' is not a member of 'RH_RF24'

  rf24.setModemConfig(RH_RF24::POCSAG_1b_4d5); 
There was an error, the version of the library used,

**Comment by jumbo77** [comment]
you can try GFSK_Rb0_5Fd1 instead

**Comment by mjkdz** [comment]
thanks


On 7/28/2021 ***@***.***> wrote：

Closed #1.
